### PR TITLE
Fix some reflection warnings.

### PR DESCRIPTION
**Pull request by wiseman**
I see you don't have issues enabled on this repository so I wasn't sure if pull requests were welcome, but here's one in case they are :)

### CODE REVIEW

**Comment by wiseman** [comment]
(Oops, my mistake: issues are enabled.)  Tested with `lein midje`, tests pass.

**Comment by aphyr** [comment]
Terrific, thanks :)

**Comment by aphyr** [comment]
Oh, haha, I don't have access to maintain this repo any more. Maybe @ztellman could merge for me?

**Comment by aphyr** [comment]
Thank you, Zach. :)

**Pull request merged**
